[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pylint.messages_control] 
disable = [
	'trailing-whitespace',
	'too-many-ancestors'
        ]
generated-members = [
                  'torch.',
                  ]	